Import("env")
Import("lib")
Import("libs")

env.Program("type_object", "type_object.c", LIBS=libs)
env.Program("recursive", "recursive.c", LIBS=libs)
env.Program("parse_object", "parse_object.c", LIBS=libs)
env.Program("multi_type", "multi_type.c", LIBS=libs)
