Import("env")

clientobjs = env.SharedObject(["linda.c", "value.c", "tuple.c", "message.c", "messageread.c", "tuplespace.c", "refcount.c", "tuple_queue.c", "threading.c"])
serverobjs = env.SharedObject(["linda_server.c", "value.c", "tuple.c", "message.c", "messageread.c", "tuplespace.c", "refcount.c", "tuple_queue.c", "threading-dummy.c"])

Return("clientobjs", "serverobjs")
