import sys

Import("env")

if sys.platform == "win32":
    threading = ["threading-dummy.c"]
else:
    threading = ["threading.c"]

clientobjs = env.SharedObject(["linda.c", "message.c", "messageread.c", "tuplespace.c", "refcount.c", "utils.c"] + threading)
serverobjs = env.SharedObject(["linda_server.c", "message.c", "messageread.c", "tuplespace.c", "refcount.c", "threading-dummy.c", "utils.c"])

Return("clientobjs", "serverobjs")
