Import("env")

clientobjs = env.SharedObject(["linda.c", "tuplespace.c", "value.c", "message.c", "tsref.c", "typemap.c"])
serverobjs = env.SharedObject(["linda-server.c", "value.c", "message.c", "tsref.c", "typemap.c"])

Return("clientobjs", "serverobjs")
